# -*- coding: utf-8 -*-
"""ITM618_FinalProject_PythonFile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13Zuov5tWuGKel6xZ0Bsr9-Zzka644Hgh
"""

from google.colab import drive
drive.mount('/content/drive')

import os
os.getcwd()

#Importing Libraries
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib as mpl
import seaborn as sns

#Importing the datasets and assigning them a name. trainSet for the training data, and testSet for the testing data.

trainSet = pd.read_csv("/content/drive/MyDrive/trainset.csv")
testSet = pd.read_csv("/content/drive/MyDrive/testset.csv")

trainSet

testSet

#Checking the values within each column

print("unique values of job", trainSet.job.unique())
print("unique values of marital", trainSet.marital.unique())
print("unique values of education", trainSet.education.unique())
print("unique values of housing", trainSet.housing.unique())
print("unique values of loan", trainSet.loan.unique())
print("unique values of contact", trainSet.contact.unique())
print("unique values of month", trainSet.month.unique())
print("unique values of day_of_week", trainSet.day_of_week.unique())
print("unique values of poutcome", trainSet.poutcome.unique())
print("unique values of Subscribed", trainSet.Subscribed.unique())

#Cleaning the data here. Removing any rows that contain the value of 'unknown'

trainSet = trainSet[trainSet['job'] != 'unknown']
trainSet = trainSet[trainSet['marital'] != 'unknown']
trainSet = trainSet[trainSet['education'] != 'unknown']
trainSet = trainSet[trainSet['housing'] != 'unknown']
trainSet = trainSet[trainSet['loan'] != 'unknown']

testSet = testSet[testSet['job'] != 'unknown']
testSet = testSet[testSet['marital'] != 'unknown']
testSet = testSet[testSet['education'] != 'unknown']
testSet = testSet[testSet['housing'] != 'unknown']
testSet = testSet[testSet['loan'] != 'unknown']

#Checking both data sets to see if the row count has gone down by removing the 'unknown' data

trainSet

testSet

#Checking unique values to see if there are any 'unknown' values remaining

print("unique values of job", trainSet.job.unique())
print("unique values of marital", trainSet.marital.unique())
print("unique values of education", trainSet.education.unique())
print("unique values of housing", trainSet.housing.unique())
print("unique values of loan", trainSet.loan.unique())
print("unique values of contact", trainSet.contact.unique())
print("unique values of month", trainSet.month.unique())
print("unique values of day_of_week", trainSet.day_of_week.unique())
print("unique values of poutcome", trainSet.poutcome.unique())
print("unique values of Subscribed", trainSet.Subscribed.unique())

#Importing LabelEncoder for the target variable

from sklearn.preprocessing import LabelEncoder

le_target = LabelEncoder()
le_target.fit(trainSet['Subscribed'])
trainSet['target_class_val'] = le_target.transform(trainSet['Subscribed'])
testSet['target_class_val'] = le_target.transform(testSet['Subscribed'])

pip install category_encoders

#Using OrdinalEncoder to change categorical/qualitative data into numeric data for analysis purposes

from category_encoders import OrdinalEncoder

job_mapping = [{'col': 'job', 'mapping': {'blue-collar': 0, 'entrepreneur': 1, 'technician': 2, 'housemaid': 3, 'unknown': 4, 'services': 5, 'management': 6, 'admin.': 7, 'student': 8, 'unemployed': 9, 'self-employed': 10, 'retired': 11 }}]
oe_job = OrdinalEncoder(mapping=job_mapping)
oe_job.fit(trainSet['job'])
trainSet['job_val'] = oe_job.transform(trainSet['job'])
testSet['job_val'] = oe_job.transform(testSet['job'])

marital_mapping = [{'col': 'marital', 'mapping': {'divorced': 0, 'married': 1, 'single': 2, 'unknown': 3 }}]
oe_marital = OrdinalEncoder(mapping=marital_mapping)
oe_marital.fit(trainSet['marital'])
trainSet['marital_val'] = oe_marital.transform(trainSet['marital'])
testSet['marital_val'] = oe_marital.transform(testSet['marital'])

education_mapping = [{'col': 'education', 'mapping': {'basic.4y': 0, 'university.degree': 1, 'basic.9y': 2, 'professional.course': 3, 'unknown': 4, 'high.school': 5, 'basic.6y': 6, 'illiterate': 7 }}]
oe_education = OrdinalEncoder(mapping=education_mapping)
oe_education.fit(trainSet['education'])
trainSet['education_val'] = oe_education.transform(trainSet['education'])
testSet['education_val'] = oe_education.transform(testSet['education'])

housing_mapping = [{'col': 'housing', 'mapping': {'yes': 0, 'no': 1, 'unknown': 2}}]
oe_housing = OrdinalEncoder(mapping=housing_mapping)
oe_housing.fit(trainSet['housing'])
trainSet['housing_val'] = oe_housing.transform(trainSet['housing'])
testSet['housing_val'] = oe_housing.transform(testSet['housing'])

loan_mapping = [{'col': 'loan', 'mapping': {'no': 0, 'yes': 1, 'unknown': 2}}]
oe_loan = OrdinalEncoder(mapping=loan_mapping)
oe_loan.fit(trainSet['loan'])
trainSet['loan_val'] = oe_loan.transform(trainSet['loan'])
testSet['loan_val'] = oe_loan.transform(testSet['loan'])

contact_mapping = [{'col': 'contact', 'mapping': {'telephone': 0, 'cellular': 1}}]
oe_contact = OrdinalEncoder(mapping=contact_mapping)
oe_contact.fit(trainSet['contact'])
trainSet['contact_val'] = oe_contact.transform(trainSet['contact'])
testSet['contact_val'] = oe_contact.transform(testSet['contact'])

month_mapping = [{'col': 'month', 'mapping': {'mar': 0, 'apr': 1, 'may': 2, 'jun': 3, 'jul': 4, 'aug': 5, 'sep': 6, 'oct': 7, 'nov': 8, 'dec': 9}}]
oe_month = OrdinalEncoder(mapping=month_mapping)
oe_month.fit(trainSet['month'])
trainSet['month_val'] = oe_month.transform(trainSet['month'])
testSet['month_val'] = oe_month.transform(testSet['month'])

day_of_week_mapping = [{'col': 'day_of_week', 'mapping': {'mon': 0, 'tue': 1, 'wed': 2, 'thu': 3, 'fri': 4}}]
oe_day_of_week = OrdinalEncoder(mapping=day_of_week_mapping)
oe_day_of_week.fit(trainSet['day_of_week'])
trainSet['day_of_week_val'] = oe_day_of_week.transform(trainSet['day_of_week'])
testSet['day_of_week_val'] = oe_day_of_week.transform(testSet['day_of_week'])

poutcome_mapping = [{'col': 'poutcome', 'mapping': {'nonexistent': 0, 'failure': 1, 'success': 2}}]
oe_poutcome = OrdinalEncoder(mapping=poutcome_mapping)
oe_poutcome.fit(trainSet['poutcome'])
trainSet['poutcome_val'] = oe_poutcome.transform(trainSet['poutcome'])
testSet['poutcome_val'] = oe_poutcome.transform(testSet['poutcome'])

housing_mapping = [{'col': 'housing', 'mapping': {'yes': 0, 'no': 1, 'unknown': 2}}]
oe_housing = OrdinalEncoder(mapping=housing_mapping)
oe_housing.fit(trainSet['housing'])
trainSet['housing_val'] = oe_housing.transform(trainSet['housing'])
testSet['housing_val'] = oe_housing.transform(testSet['housing'])

#Checking datasets to see if the new numeric columns are present

trainSet

testSet

#Importing sci-kit learn tree library for creating the decision tree

from sklearn import tree

train_y = trainSet['target_class_val']
train_X = trainSet[['age', 'job_val', 'marital_val', 'education_val', 'housing_val', 'loan_val', 'contact_val', 'month_val', 'day_of_week_val', 'duration', 'month_val', 'poutcome_val']]

test_y = testSet['target_class_val']
test_X = testSet[['age', 'job_val', 'marital_val', 'education_val', 'housing_val', 'loan_val', 'contact_val', 'month_val', 'day_of_week_val', 'duration', 'month_val', 'poutcome_val']]

#Testing the trainSet by creating a decision tree based on that

treeTrain1 = tree.DecisionTreeClassifier(max_depth = 5)
treeTrain1 = treeTrain1.fit(train_X, train_y)
accuracy = []

scoreTrain1 = treeTrain1.score(train_X, train_y)
accuracy.append(score)

print("Accuracy of the test data is ", scoreTrain1 * 100, '%')

#Because the accuracy is a 100%, this means that the data is overfitting and would need pruning. This is where we use the DecisionTreeClassifier Depth test to see which one fits it best.

from sklearn.tree import DecisionTreeClassifier

# List of values to try for max_depth:
max_depth_range = list(range(1, 6))
# List to store the accuracy for each value of max_depth:
accuracy = []
for depth in max_depth_range:
    clf = DecisionTreeClassifier(max_depth = 5, random_state = 0)
    clf.fit(train_X, train_y)
    score = clf.score(train_X, train_y)
    accuracy.append(score)
score

#Checking the classification report of the train set decision tree

predictions = treeTrain1.predict(train_X)
predictions
from sklearn.metrics import classification_report
print(classification_report(train_y, predictions))

#Testing a second tree with max depth of 4 and min samples split of 100 to reduce overfitting

treeTrain2 = tree.DecisionTreeClassifier(max_depth = 4, min_samples_split = 100)
treeTrain2 = treeTrain2.fit(train_X, train_y)
tree.plot_tree(treeTrain2)

from sklearn import tree

#Checking the accuracy of our data set for the test data, since this is also 100%, we will use the depth and samples split.

treeTest = tree.DecisionTreeClassifier(max_depth = 5, min_samples_split = 500)
treeTest = treeTest.fit(test_X, test_y)
accuracy = []


score = treeTest.score(test_X, test_y)
accuracy.append(score)


print("Accuracy of test data is ", score * 100, "%")

tree.plot_tree(treeTest)

#Visualizing the decision tree through graphwiz

import graphviz

dot_data_test = tree.export_graphviz(treeTest, out_file=None,
                    feature_names=['age', 'job_val', 'marital_val', 'education_val', 'housing_val', 'loan_val', 'contact_val', 'month_val', 'day_of_week_val', 'duration', 'month_val', 'poutcome_val'],
                    class_names=testSet.Subscribed.unique(),
                    filled=True, rounded=True,
                    special_characters=True)
graph_test = graphviz.Source(dot_data_test)
graph_test

#Checking the classification report of the test data decision tree

predictions = treeTest.predict(test_X)
predictions
from sklearn.metrics import classification_report
print(classification_report(test_y, predictions))

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Creating a loop for the nearest neighbours to find one with the best accuracy


from sklearn.neighbors import KNeighborsClassifier

j = 3
max_acc = 0
n_neighbors = 0
from category_encoders.utils import sklearn
for i in range(17):
  knn = KNeighborsClassifier(n_neighbors=j)
  knn = knn.fit(test_X, test_y)
  acc = sklearn.metrics.accuracy_score(test_y, knn.predict(test_X))
  print(f"neighbors: {j} and accuracy: {acc}")
  j = j+2
  if acc > max_acc:
    max_acc = acc
    h = j-2
print (f"max accuracy is: {max_acc} with {h} neighbours")

knn = KNeighborsClassifier(n_neighbors = h)

knn.fit(test_X, test_y)

predicted_labels = knn.predict(test_X)

#Classification report for the KNN model

y_predicted=knn.predict(testSet[['age', 'job_val', 'marital_val', 'education_val', 'housing_val', 'loan_val', 'contact_val', 'month_val', 'day_of_week_val', 'duration', 'month_val', 'poutcome_val']])
import sys
np.set_printoptions(threshold = sys.maxsize)
y_predicted

from sklearn.metrics import confusion_matrix
confusion_matrix(y_predicted, testSet['target_class_val'], labels=[1,0])

TP, FP, FN, TN = confusion_matrix(y_predicted, testSet['target_class_val'], labels=[1,0]).ravel()
(TP, FP, FN, TN)


print(sklearn.metrics.classification_report(testSet['target_class_val'], y_predicted))

#importing the library for logistic regression

from sklearn.linear_model import LogisticRegression
from sklearn import metrics
logreg = LogisticRegression()
logreg.fit(test_X, test_y)

#predicting the accuracy of this model

y_pred = logreg.predict(test_X)
print('Accuracy of logistic regression classifier on test set: {:.2f}'.format((logreg.score(test_X, test_y))))

#Outputting the confusion matrix of this model

from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(test_y, y_pred)
print(confusion_matrix)

#Creating the classification report for this logistics regression model

from sklearn.metrics import classification_report
print(classification_report(test_y, y_pred))
